name: Update GitHub Profile Summary Cards

on:
  schedule:
    - cron: "0 2 * * *"   # Every day at 02:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout profile-cards branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: profile-cards
          persist-credentials: false

      - name: Generate GitHub Profile Summary Cards
        uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: grazulex
          BRANCH_NAME: profile-cards
          UTC_OFFSET: "+2"
          AUTO_PUSH: true  # Let the action commit & push

      # Optional: clear cache for pinned repo cards (uncomment & duplicate per repo if needed)
      # - name: Clear GitHub Readme Stats cache (example for laravel-arc)
      #   run: curl -s -X POST "https://github-readme-stats.vercel.app/api/pin/?username=grazulex&repo=laravel-arc"
