name: Update GitHub Profile Summary Cards

on:
  schedule:
    - cron: "0 2 * * *" # Chaque jour à 2h UTC
  workflow_dispatch: # Permet de le lancer manuellement

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate GitHub Profile Summary Cards
        uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          USERNAME: grazulex
          # Choisis le thème : github_dark, dracula, monokai, etc.
          THEME: github_dark

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "🔄 Update GitHub Profile Summary Cards"
          git push

      - name: Clear GitHub Readme Stats cache
        run: curl -s -X POST https://github-readme-stats.vercel.app/api/pin/?username=grazulex&repo=laravel-arc

